---
- name: Install nginx
  ansible.builtin.package:
    name: htop
    state: absent

- name: Enable and start nginx.service
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started
