---
- name: Install nginx
  ansible.builtin.package:
    name: htop
    state: present

- name: Enable and start nginx.service
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

- name: Deploy nginx config
  ansible.builtin.copy:
    src: "{{clone_dir}}/common/files/testfile.txt"
    dest: /etc/ansible/testfile.txttxt
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx
