- hosts: lxbm

  # roles:
  # - nginx: "{{clone_dir}}/roles/nginx"

  tasks:
  # - name: Install nginx
  #   ansible.builtin.package:
  #     name: htop
  #     state: present

  # - name: Enable and start nginx.service
    # ansible.builtin.service:
    #   name: nginx
    #   enabled: yes
    #   state: started
  - name: Deploy nginx config
    ansible.builtin.copy:
      src: files/testfile.txt
      dest: /etc/ansible/testfile.txttxt
      owner: root
      group: root
      mode: '0644'
    notify: Restart Nginx


  # handlers:
  # - name: Restart Nginx
  #   service:
  #     name: nginx
  #     state: restarted
- import_playbook: nginx.yml
