---
- name: Playbook for the lxbm node
  hosts: lxbm

  roles:
    - common
    - nginx

  tasks:
  - name: Deploy nginx config
    ansible.builtin.copy:
      src: files/testfile.txt
      dest: /etc/ansible/testfile.txt
      owner: root
      group: root
      mode: '0644'
    notify: Restart Nginx  # Depends on the handler defined in the nginx role
