---
- name: Playbook for the lxbm node
  hosts: lxbm

  roles:
    - common
    - nginx

  tasks:
  - name: Deploy nginx config
    ansible.builtin.copy:
      src: "{{item}}"
      dest: /etc/nginx
      owner: root
      group: root
      mode: '0644'
    notify: Restart Nginx  # Depends on the handler defined in the nginx role
    loop:
      - files/lxbm-nginx-conf/common
      - files/lxbm-nginx-conf/sites-enabled
      - files/lxbm-nginx-conf/nginx.conf
