---
- hosts: all
  remote_user: root

  vars:
    branch: master
    logfile: /var/log/ansible-pull.log

  tasks:

  - name: Ansible-pull.
    ansible.builtin.cron:
      name: "Ansible-pull"
      minute: "32"
      hour: "7-20"
      job: >
        ansible-pull
        --only-if-changed
        --checkout {{branch}}
        --directory /etc/ansible/ansible-cm
        --inventory-file "$(hostname --short),"
        --url https://github.com/soofstad/ansible-cm > {{logfile}} 2>&1
      cron_file: /etc/crontab
      user: root
