---
- name: Upgrade packages and register reboot schedule
  hosts: all
  tasks:

  - name: Upgrade all packages (Debian)
    apt:
      name: '*'
      state: latest
    when: ansible_facts['os_family'] == "Debian"

  - name: Upgrade all packages (Red Hat)
    yum:
      name: '*'
      state: latest
    when: ansible_facts['os_family'] == "RedHat"

  - name: Reboot every month
    ansible.builtin.cron:
      name: "Reboot"
      minute: "12"
      hour: "02"
      day: "2"
      job: systemctl reboot
      cron_file: /etc/crontab
      user: root
